cuentas/urls.py
from django.contrib import admin
from django.urls import path
from django.shortcuts import redirect
from django.urls import include
from .views import login_view, logout_view

urlpatterns = [
    path('login/', login_view, name='login_view'),
    path('logout/', logout_view, name='logout_view'),
]

ferreteria/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productos.urls')),
    path('', include('cuentas.urls')),
]

productos/models.py
from django.db import models

class Proovedor(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
class Marca(models.Model):
    nombre = models.CharField(max_length=100)
    
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    marca = models.ForeignKey("Marca", on_delete=models.SET_NULL, null=True, blank=True)




class Precio(models.Model):
    producto = models.ForeignKey("Producto", on_delete=models.CASCADE)
    proovedor = models.ForeignKey("Proovedor" , on_delete=models.CASCADE)
    precio = models.DecimalField(max_digits=10 , decimal_places=2)
    fecha_actualizacion = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.producto} - {self.proovedor} : {self.precio}'

templates/eleccion_lista.html
{% extends "base/base.html" %}

    {% block content %}

    <div class="container-list">
        <H2>Elije que lista deseas ver</H2>
        <a href="{% url 'listar_productos_fenix' %}" class="btn btn-dark">Fenix</a>
        <a href="{% url 'listar_productos_palomar' %}" class="btn btn-dark">Palomar</a>
        <a href="{% url 'listar_productos_electrimat' %}" class="btn btn-dark">Electrimat</a>
    </div>

    <style>
        .container-list{
            text-align: center;
        }
    </style>

{% endblock %}

templates/listar_productos_electrimat.html
{% extends "base/base.html" %}
    {% block content %}
        <h1>{{ precio.proovedor.nombre }}</h1>
        <h1>Subir excel de ELECTRIMAT</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Subir</button>
        </form>
        <div class="btn-container">
            <a href="{% url 'listar_productos_fenix' %}" class="btn btn-outline-dark">Ver Lista Fenix</a>
            <a href="{% url 'listar_productos_palomar' %}" class="btn btn-outline-dark">Ver Lista Palomar</a>
        </div>
        <h1 class="title"> LISTA DE PRODUCTOS ELECTRIMAT</h1>
        <table class="tabla">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>NOMBRE</th>
                    <th>PRECIO</th>
                    <th>PROOVEDOR</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                    {% for precio in producto.precio_set.all %}
                        {% if precio.proovedor.nombre == 'Electrimat' %}
                            <tr>
                                <td>{{ precio.id }}</td>
                                <td>{{ producto.nombre }}</td>
                                <td>{{ precio.precio }}</td>
                                <td>
                                    {{ precio.proovedor.nombre}}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
        <style>
            .btn-container {
                text-align: center;
                margin: 20px 0;
            }
        
            .btn-container .btn {
                margin: 0 10px;
            }
        </style>
    {% endblock %}

templates/listar_productos_fenix.html
        {% extends "base/base.html" %}
    {% block content %}
        <h1>{{precio.proovedor.nombre}} </h1>
            <h1>Subir excel de SANITARIOS FENIX</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Subir</button>
            </form>
            <div class="btn-container">
                <a href="{% url 'listar_productos_electrimat' %}" class="btn btn-outline-dark">Ver Lista Electrimat</a>
                <a href="{% url 'listar_productos_palomar' %}" class="btn btn-outline-dark">Ver Lista Palomar</a>
            </div>
            <h1 class="title">LISTA DE PRODUCTOS FENIX</h1>
            <table class="tabla" border="1">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Proovedor</th>
                    </tr>
                </thead>
                <tbody>
                        {% for precio in precios%}
                            {% if precio.proovedor.nombre == 'Distribuidora Sanitaria Fenix' %}
                                <tr>
                                    <td>
                                    {% if precio.precio %}
                                            {{ precio.id }}
                                        {% else %}
                                        
                                        {% endif %}
                                    </td>
                                    <td>{{ precio.producto.nombre }}</td>
                                    <td>
                                        {% if precio.precio %}
                                            {{ precio.precio }}
                                        {% else %}
                                        
                                        {% endif %}
                                    </td>
                                    <td>
                                        {{ precio.proovedor.nombre}}
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}

                </tbody>
            </table>
        <style>
            .btn-container {
                text-align: center;
                margin: 20px 0;
            }
        
            .btn-container .btn {
                margin: 0 10px;
            }
        </style>
    {% endblock content %}

templates/listar_productos_palomar.html
{% extends "base/base.html" %}
    {% block content %}
        <h1>{{ precio.proovedor.nombre }}</h1>
        <h1>Subir excel de PALOMAR</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Subir</button>
        </form>
        <div class="btn-container">
            <a href="{% url 'listar_productos_electrimat' %}" class="btn btn-outline-dark">Ver Lista Electrimat</a>
            <a href="{% url 'listar_productos_fenix' %}" class="btn btn-outline-dark">Ver Lista Fenix</a>
        </div>
        <h1 class="title">LISTA DE PRODUCTOS PALOMAR</h1>
        <table class="tabla">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>NOMBRE</th>
                    <th>PRECIO (X100%)</th>
                    <th>MARCA</th>
                    <th>PROOVEDOR</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                    {% for precio in producto.precio_set.all %}
                        {% if precio.proovedor.nombre == 'Distrito Palomar' %}
                            <tr>
                                <td>{{ precio.id }}</td>
                                <td>{{ producto.nombre }}</td>
                                <td>{{ precio.precio }}</td>
                                <td>{{ producto.marca.nombre }}</td>
                                <td>
                                    {{ precio.proovedor.nombre}}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    <style>
        .btn-container {
            text-align: center;
            margin: 20px 0;
        }
        
        .btn-container .btn {
                margin: 0 10px;
        
        }
    </style>
    {% endblock %}